services:
  nacos:
    image: nacos/nacos-server:v3.2.1
    container_name: shopmax-nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: ""
      JVM_XMS: 256m
      JVM_XMX: 256m
      JVM_XMN: 128m
      NACOS_AUTH_ENABLE: "true"
      NACOS_AUTH_TOKEN: "U2hvcE1heC1OYWNvcy1BdXRoLVRva2VuLTIwMjQ="
      NACOS_AUTH_IDENTITY_KEY: "serverIdentity"
      NACOS_AUTH_IDENTITY_VALUE: "security"
    volumes:
      - ./data/nacos/logs:/home/nacos/logs
    networks:
      - shopmax-net
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: shopmax-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    networks:
      - shopmax-net
    restart: unless-stopped

  srs:
    image: ossrs/srs:6
    container_name: shopmax-srs
    ports:
      - "1935:1935"   # RTMP 推流端口
      - "8085:8080"   # HTTP-FLV/HLS 输出端口
      - "1985:1985"   # SRS HTTP API 端口
    volumes:
      - ./docker/srs/conf:/usr/local/srs/conf
      - ./docker/srs/data:/usr/local/srs/data
      - ./docker/srs/record:/usr/local/srs/record
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - shopmax-net
    restart: unless-stopped

networks:
  shopmax-net:
    driver: bridge
