server:
  port: 8084

spring:
  application:
    name: shop-payment-service

  config:
    import: optional:nacos:${spring.application.name}.yaml

  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        enabled: true
        server-addr: localhost:8848
      config:
        enabled: true
        server-addr: localhost:8848
        file-extension: yaml

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopmax?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: aptx4869
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/**/*.xml

# JWT配置
jwt:
  secret: shopmax-secret-key-2026-for-jwt-signing-and-verification
  expiration: 86400000

# 支付网关配置
payment:
  notify-base-url: https://511976c3.r7.cpolar.cn
  frontend-base-url: http://localhost:3100
  alipay:
    sandbox: true
    # 从 https://open.alipay.com/develop/sandbox/app 获取以下参数
    app-id: 9021000164626534   # 沙箱APPID
    # 沙箱网关地址
    gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    # 应用私钥(PKCS8格式)
    private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCMezZiBGw/8OalGjfJzhJQ8QBXwuEhphAleF5PAW1qUYQhMTIWA1pNhukbjwijNyIxaeiEz1G+FxUePFvNwWDXm2rIOiPAYsh/WDggP05uixN/QESy7sGad4xdcHOfAsv1bGXkqAOqHpVj70y5xawDiqqcHHxgz13Z8s0WRzKyMAt8fm7W12TuqWF5gwFJWT6Nay+5simxuzpJh0WGcgtDAPLYaogcfcVxhJgasqR+xYCmwH8TlA44w9r7xpR/nNRzXvIwQf2b+2YRysvg5y/6fWImvtA1jxUw9yDjb/njHUeKwMC07R/Fg+xGKD/I4Phm+S/leXkURmnu0liCJLlVAgMBAAECggEAbc++of3tFEpeML7+zvwLq0PITdHjI+dohbHCnqVx/wK7cyq+iSCTzThhLY6wZM0rKE8uV+qrbhkjA+CQrpSz+7XcUanI2pEdQxYVwXda+uQyGG2HhgtGQVWj3kKRzsFj53OVbpi7TJbdliGv6yOOo7IYTTGjNBXEuiKml/yNr2TfU/524DzG2ox4jy7OpbkMa0dt+Daf5pDoQ3aETxoprhr4vq6JXdVxs1bTT1PilO8uXpxaTarDixo7XLV3rkbAvZK1ifoAEoS8blwXnHjrsU0/FTBbnuD41JWqUnUNtCgsxwj+5pF8lvfjNWqTuU1i3ELMT3j9fTUzDnws2mwHnQKBgQDPmPAB26H9TStznlwPAPN0zpoA2ClUuWDz1Uy5sZLHVmO29aIl89x/PJUV0eQQp4XCF2jXRXhb8qBUnK5jhr4poACiP2QhyvPh2ruUPi1w6/+nD47sWkA2RuND+Y9ZVRkRte8j6u7FpuvOX8PlXaWgvHL2UpO4eIyZTOQPcSyR9wKBgQCtPECM63B0tjfyvrn1gNomxWOfupatskiFaBESIypZUNlitzIu6ndUkJIwQ90f7Wha16r2tx7xiKg/VP2232HO1CF3VxN30hCSU5xT2hJSAJROXW9hS2BsGgNRWh3zndzypfiyFYs4sPBdrWU2RmMapwXjxWRyIHPEsN2+O2A8EwKBgQCIMHrznRSuShwBY5hdN3B/5rHdb/HdZSgXjo0hHT9/ikssUgSoBU1YI3Ritil6S4xSgm0DHM4S9B7+ozM8k77ZK+B+kDuud6h7OLXqUMga1pgHDwviPmr1sJeTlnrWTh9+IO7bj1pJTHJSFz06ka8AveBlfFLwqBUE1Q6gmsx0jQKBgF+sIPIyrN6oK+nyD31YdiJnbQev4rt29LpIqPTdWuwMzKHKDvr+Hn0jgrkJIbwaP0G8Tf0HUR2PnWusopo2cCvr17ey7VuFNgW6C2H705ZaH43P6E1RdaT+EMsC+/upOXcA1oJzh3n9riHuOzFoWh9EEuqh/0FQTt9X1n7TB+jlAoGBAJh+u5TrKxCZbgONXqG5x5A82nbBoykcsqy8DaHi9EXa6IcvYP+55L+4XjpgkjHQegeKNThplXsSqYKYjSYeFEKfcuRfR5fw5t9FlRET/fY5LdG7MSa2sr/+Y+83YyUAY/PpRwBYGqL28cTIUimIx91D81iupRn6hrt634W6Tqpm
    # 支付宝公钥
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiesqTy3unfg4onOxOn0OH8GXJV+IHUCj2Ra2mIDEatfdvKP+dZkOoknGzRb1yRMhafrSVmEV2FVYzG2qeAms2XnshNeFIRisZQREuFBGBXaofX63IgiSvkAENXls3QiAAtmK6c9RzZCGFqaYgs4jc6bLx1X9erPOlDE2PnIRUSgM1rlFGkKiqT1UNPvqTHSyeGvjna2byBalcF8AtsxtXvtg0N9jzy+lWJsEw7BI0HytfIzsu967Hb5kSWaQd+JgECJS0eqLzt2xRKpRwOqKW4R6eH3gHtkVzQCM/4NfImYcJmvWspPxcH2CRv6SRc0FVGtZoxsGe1uFx+yI2KTBbQIDAQAB

  wechat-pay:
    mock: true
    #无营业执照，暂时搁置(需开发时设置 mock: false)
#    merchant-id: ""              # 微信支付商户号
#    api-v3-key: ""               # APIv3密钥（32位，商户平台 -> API安全 -> APIv3密钥）
#    merchant-serial-number: ""   # 商户证书序列号
#    private-key: ""              # 商户API私钥（apiclient_key.pem 文件内容）
#    app-id: "wxb41728c4b369c8b3"                   # 小程序/公众号 AppID

# 日志配置
logging:
  level:
    com.shop.payment: debug
    com.shop.payment.mapper: debug
