apiVersion: v1
kind: ConfigMap
metadata:
  name: shopmax-config
  namespace: shopmax
data:
  # 数据库配置
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "shopmax"
  DB_USERNAME: "root"
  # Redis配置
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  # Nacos配置
  NACOS_SERVER_ADDR: "nacos:8848"
  NACOS_USERNAME: "nacos"
  # JWT配置
  JWT_SECRET: "shopmax-secret-key-2026-for-jwt-signing-and-verification"
  # XXL-JOB配置
  XXL_JOB_ADMIN_ADDR: "http://xxl-job-admin:8080/xxl-job-admin"
  # ELK配置
  LOGSTASH_HOST: "logstash"
  LOGSTASH_PORT: "5044"
