<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.shop</groupId>
        <artifactId>shop-backend</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>shop-common</artifactId>
    <packaging>pom</packaging>

    <name>shop-common</name>
    <description>公共模块父工程</description>

    <modules>
        <module>shop-common-core</module>
        <module>shop-common-web</module>
        <module>shop-common-redis</module>
        <module>shop-common-security</module>
        <module>shop-common-storage</module>
    </modules>
</project>
